### ISSUE TITLE
[Bug Report] Material Kit Theme - Portfolio Dark Demo doesn't display correctly in Edge

### ISSUE THREAD

**Issue by s08cz1** [vuetifyjs/issues#1]
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.4
**Browsers:** Edge 17.17134
**OS:** Windows 10

### Steps to reproduce
Go to https://material-portfolio-dark.vuetifyjs.com/ using Edge browser

### Expected Behavior
Side menu is displayed, title page is displayed on start (works fine in FF and Chrome)

### Actual Behavior
Side menu does not display and the website loads on "What I've done" page

### Reproduction Link
<a href="https://jsfiddle.net/f5wd0anz/" target="_blank">https://jsfiddle.net/f5wd0anz/</a>

### Other comments
Edge console displays following error "SCRIPT1028: SCRIPT1028: Expected identifier, string or number". I have no idea what versions of Vue and Vuetify your demos run on, so the answers I provided may not be relevant.

**Comment by jacekkarczmarczyk** [comment]
This repo is only for issues with [Issue Creator](https://issues.vuetifyjs.com), please use the [main repo](https://github.com/vuetifyjs/vuetify)
